/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.DecimalFormat;
import javax.swing.JButton;

/**
 *
 * @author K00243015
 */
public class TypingTutorGUI extends javax.swing.JFrame implements KeyListener{
    
    /**
     * Creates new form TypingTutorGUI
     */
    public TypingTutorGUI() {
        initComponents();
        //attach KeyListener to textArea component
        textArea.addKeyListener(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        noteLabel = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();
        textPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextPane();
        keyboardPanel = new javax.swing.JPanel();
        capsBtn = new javax.swing.JButton();
        aBtn = new javax.swing.JButton();
        sBtn = new javax.swing.JButton();
        dBtn = new javax.swing.JButton();
        fBtn = new javax.swing.JButton();
        gBtn = new javax.swing.JButton();
        hBtn = new javax.swing.JButton();
        jBtn = new javax.swing.JButton();
        kBtn = new javax.swing.JButton();
        lBtn = new javax.swing.JButton();
        semiColonBtn = new javax.swing.JButton();
        apostropheBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        backSlashBtn = new javax.swing.JButton();
        tildeBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        hyphenBtn = new javax.swing.JButton();
        equalsBtn = new javax.swing.JButton();
        backSpaceBtn = new javax.swing.JButton();
        spaceBtn = new javax.swing.JButton();
        leftBtn = new javax.swing.JButton();
        downBtn = new javax.swing.JButton();
        rightBtn = new javax.swing.JButton();
        vBtn = new javax.swing.JButton();
        bBtn = new javax.swing.JButton();
        nBtn = new javax.swing.JButton();
        mBtn = new javax.swing.JButton();
        commaBtn = new javax.swing.JButton();
        periodBtn = new javax.swing.JButton();
        questionMarkBtn = new javax.swing.JButton();
        upBtn = new javax.swing.JButton();
        rightBracketBtn = new javax.swing.JButton();
        tabBtn = new javax.swing.JButton();
        qBtn = new javax.swing.JButton();
        wBtn = new javax.swing.JButton();
        eBtn = new javax.swing.JButton();
        rBtn = new javax.swing.JButton();
        tBtn = new javax.swing.JButton();
        yBtn = new javax.swing.JButton();
        uBtn = new javax.swing.JButton();
        iBtn = new javax.swing.JButton();
        oBtn = new javax.swing.JButton();
        pBtn = new javax.swing.JButton();
        leftBracketBtn = new javax.swing.JButton();
        shiftBtn = new javax.swing.JButton();
        zBtn = new javax.swing.JButton();
        xBtn = new javax.swing.JButton();
        cBtn = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        accuracyLabel = new javax.swing.JLabel();
        accuracyValue = new javax.swing.JLabel();
        correctCharactersLabel = new javax.swing.JLabel();
        correctCharactersValue = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        difficultyComboBox = new javax.swing.JComboBox();
        incorrectCharactersLabel = new javax.swing.JLabel();
        incorrectCharactersValue = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Typing Tutor");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        noteLabel.setText("Note: Clicking The Buttons With Your Mouse Will Not Perform Any Action.");

        textLabel.setForeground(new java.awt.Color(255, 0, 0));
        textLabel.setText("Type Some Text Using Your Keyboard. The Keys You Press Will Be Highlighted And The Text Will Be Displayed.");

        textArea.setEditable(false);
        textArea.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(textArea);

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noteLabel)
                            .addComponent(textLabel)))
                    .addComponent(textPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        keyboardPanel.setBackground(new java.awt.Color(153, 153, 153));

        capsBtn.setText("Caps");

        aBtn.setText("A");

        sBtn.setText("S");

        dBtn.setText("D");

        fBtn.setText("F");

        gBtn.setText("G");

        hBtn.setText("H");

        jBtn.setText("J");

        kBtn.setText("K");

        lBtn.setText("L");

        semiColonBtn.setText(";");

        apostropheBtn.setText("'");

        returnBtn.setText("Enter");

        backSlashBtn.setText("\\");

            tildeBtn.setText("~");

            oneBtn.setText("1");

            twoBtn.setText("2");

            threeBtn.setText("3");

            fourBtn.setText("4");

            fiveBtn.setText("5");

            sixBtn.setText("6");

            sevenBtn.setText("7");

            eightBtn.setText("8");

            nineBtn.setText("9");

            zeroBtn.setText("0");

            hyphenBtn.setText("-");

            equalsBtn.setText("=");

            backSpaceBtn.setText("BackSpace");

            spaceBtn.setText("Space");

            leftBtn.setText("<");

            downBtn.setText("\\/");

            rightBtn.setText(">");

            vBtn.setText("V");

            bBtn.setText("B");

            nBtn.setText("N");

            mBtn.setText("M");

            commaBtn.setText(",");

            periodBtn.setText(".");

            questionMarkBtn.setText("?");

            upBtn.setText("^");

            rightBracketBtn.setText("]");

            tabBtn.setText("Tab");

            qBtn.setText("Q");

            wBtn.setText("W");

            eBtn.setText("E");

            rBtn.setText("R");

            tBtn.setText("T");

            yBtn.setText("Y");

            uBtn.setText("U");

            iBtn.setText("I");

            oBtn.setText("O");

            pBtn.setText("P");

            leftBracketBtn.setText("[");

            shiftBtn.setText("Shift");

            zBtn.setText("Z");

            xBtn.setText("X");

            cBtn.setText("C");

            javax.swing.GroupLayout keyboardPanelLayout = new javax.swing.GroupLayout(keyboardPanel);
            keyboardPanel.setLayout(keyboardPanelLayout);
            keyboardPanelLayout.setHorizontalGroup(
                keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(keyboardPanelLayout.createSequentialGroup()
                    .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(keyboardPanelLayout.createSequentialGroup()
                            .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(capsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(keyboardPanelLayout.createSequentialGroup()
                                    .addComponent(qBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(wBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(yBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(uBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(iBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(oBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(leftBracketBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rightBracketBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(backSlashBtn))
                                .addGroup(keyboardPanelLayout.createSequentialGroup()
                                    .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(keyboardPanelLayout.createSequentialGroup()
                                            .addComponent(aBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(sBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(gBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(kBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(semiColonBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(apostropheBtn))
                                        .addComponent(leftBtn))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(keyboardPanelLayout.createSequentialGroup()
                                            .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(downBtn)
                                                .addComponent(upBtn))
                                            .addGap(5, 5, 5)
                                            .addComponent(rightBtn))
                                        .addComponent(returnBtn)))))
                        .addGroup(keyboardPanelLayout.createSequentialGroup()
                            .addComponent(tildeBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(oneBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(twoBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(threeBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fourBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fiveBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sixBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sevenBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eightBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nineBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(zeroBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hyphenBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(equalsBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(backSpaceBtn))
                        .addGroup(keyboardPanelLayout.createSequentialGroup()
                            .addComponent(shiftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(zBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(xBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(keyboardPanelLayout.createSequentialGroup()
                                    .addComponent(cBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(vBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(commaBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(periodBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(questionMarkBtn)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            keyboardPanelLayout.setVerticalGroup(
                keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(keyboardPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tildeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hyphenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(equalsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backSpaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(leftBracketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rightBracketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backSlashBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(capsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(semiColonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(apostropheBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(keyboardPanelLayout.createSequentialGroup()
                            .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(shiftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(zBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(commaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(periodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(questionMarkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(keyboardPanelLayout.createSequentialGroup()
                            .addComponent(upBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(keyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(downBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(leftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            infoPanel.setBackground(new java.awt.Color(204, 204, 204));

            accuracyLabel.setForeground(new java.awt.Color(0, 0, 0));
            accuracyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            accuracyLabel.setText("Accuracy:");

            accuracyValue.setForeground(new java.awt.Color(0, 0, 0));
            accuracyValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            accuracyValue.setText("100%");

            correctCharactersLabel.setForeground(new java.awt.Color(0, 0, 0));
            correctCharactersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            correctCharactersLabel.setText("Correct Characters:");

            correctCharactersValue.setForeground(new java.awt.Color(0, 0, 0));
            correctCharactersValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            correctCharactersValue.setText("0");

            difficultyLabel.setForeground(new java.awt.Color(0, 0, 0));
            difficultyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            difficultyLabel.setText("Difficulty:");

            difficultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select:", "[Easy] Driven Jocks", "Bog Dwarves", "Quick Brown Fox", "Zombies Arrive", "[Medium] Plaid Jackets", "Crazy Frederick", "Pluck And Zeal", "Oxygen Equipment", "Antique Ivory Buckles", "[Hard] Beautiful Gowns" }));
            difficultyComboBox.addItemListener(new java.awt.event.ItemListener()
            {
                public void itemStateChanged(java.awt.event.ItemEvent evt)
                {
                    difficultyComboBoxItemStateChanged(evt);
                }
            });

            incorrectCharactersLabel.setForeground(new java.awt.Color(0, 0, 0));
            incorrectCharactersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            incorrectCharactersLabel.setText("Incorrect Characters:");

            incorrectCharactersValue.setForeground(new java.awt.Color(0, 0, 0));
            incorrectCharactersValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            incorrectCharactersValue.setText("0");

            resetBtn.setText("Reset");
            resetBtn.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    resetBtnActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
            infoPanel.setLayout(infoPanelLayout);
            infoPanelLayout.setHorizontalGroup(
                infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(accuracyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(accuracyValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(correctCharactersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(correctCharactersValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(difficultyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(difficultyComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(incorrectCharactersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(incorrectCharactersValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            infoPanelLayout.setVerticalGroup(
                infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(accuracyLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(accuracyValue)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(correctCharactersLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(correctCharactersValue)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(incorrectCharactersLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(incorrectCharactersValue)
                    .addGap(4, 4, 4)
                    .addComponent(difficultyLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(difficultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetBtn)
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(keyboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(infoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(keyboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    //User Selects pangram they wish to type
    private void difficultyComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_difficultyComboBoxItemStateChanged
    {//GEN-HEADEREND:event_difficultyComboBoxItemStateChanged
        switch(difficultyComboBox.getSelectedIndex())
        {
            case 0:
            {
                initialize();
                //Select Option:
                break;
            }
            case 1:
            {
                initialize(); //puts all JButtons into array, sets backgroundColor & focus' textArea
                resetWindow(); //reset window to default values
                pangram = "Two driven jocks help fax my big quiz";
                textLabel.setText(pangram);
                numberOfChars = pangram.length();
                tBtn.setBackground(Color.GREEN);
                break;
            }
            case 2:
            {
                initialize(); //puts all JButtons into array, sets backgroundColor & focus' textArea
                resetWindow(); //reset window to default values
                pangram = "Fickle jinx bog dwarves spy math quiz";
                textLabel.setText(pangram);
                numberOfChars = pangram.length();
                fBtn.setBackground(Color.GREEN);
                break;
            }
            case 3:
            {
                initialize(); //puts all JButtons into array, sets backgroundColor & focus' textArea
                resetWindow(); //reset window to default values
                pangram = "The quick brown fox jumps over the lazy dog";
                textLabel.setText(pangram);
                numberOfChars = pangram.length();
                tBtn.setBackground(Color.GREEN);
                break;
            }
            case 4:
            {
                initialize(); //puts all JButtons into array, sets backgroundColor & focus' textArea
                resetWindow(); //reset window to default values
                pangram = "When zombies arrive, quickly fax judge Pat";
                textLabel.setText(pangram);
                numberOfChars = pangram.length();
                wBtn.setBackground(Color.GREEN);
                break;
            }
            case 5:
            {
                initialize(); //puts all JButtons into array, sets backgroundColor & focus' textArea
                resetWindow(); //reset window to default values
                pangram = "My girl wove six dozen plaid jackets before she quit";
                textLabel.setText(pangram);
                numberOfChars = pangram.length();
                mBtn.setBackground(Color.GREEN);
                break;
            }
            case 6:
            {
                initialize(); //puts all JButtons into array, sets backgroundColor & focus' textArea
                resetWindow(); //reset window to default values
                pangram = "Crazy Fredrick bought many very exquisite opal jewels";
                textLabel.setText(pangram);
                numberOfChars = pangram.length();
                cBtn.setBackground(Color.GREEN);
                break;
            }
            case 7:
            {
                initialize(); //puts all JButtons into array, sets backgroundColor & focus' textArea
                resetWindow(); //reset window to default values
                pangram = "The job requires extra pluck and zeal from every young wage earner";
                textLabel.setText(pangram);
                numberOfChars = pangram.length();
                tBtn.setBackground(Color.GREEN);
                break;
            }
            case 8:
            {
                initialize(); //puts all JButtons into array, sets backgroundColor & focus' textArea
                resetWindow(); //reset window to default values
                pangram = "Back in June we delivered oxygen equipment of the same size";
                textLabel.setText(pangram);
                numberOfChars = pangram.length();
                bBtn.setBackground(Color.GREEN);
                break;
            }
            case 9:
            {
                initialize(); //puts all JButtons into array, sets backgroundColor & focus' textArea
                resetWindow(); //reset window to default values
                pangram = "We promptly judged antique ivory buckles for the next prize";
                textLabel.setText(pangram);
                numberOfChars = pangram.length();
                wBtn.setBackground(Color.GREEN);
                break;
            }
            case 10:
            {
                initialize(); //puts all JButtons into array, sets backgroundColor & focus' textArea
                resetWindow(); //reset window to default values
                pangram = "Jim quickly realized that the beautiful gowns are expensive";
                textLabel.setText(pangram);
                numberOfChars = pangram.length();
                jBtn.setBackground(Color.GREEN);
                break;
            }
            default:
                break;
        }
    }//GEN-LAST:event_difficultyComboBoxItemStateChanged

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resetBtnActionPerformed
    {//GEN-HEADEREND:event_resetBtnActionPerformed
        //Reset GUI
        dispose();
        TypingTutorGUI ttg = new TypingTutorGUI();
        ttg.setVisible(true);
        ttg.initialize();
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TypingTutorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TypingTutorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TypingTutorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TypingTutorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TypingTutorGUI ttg = new TypingTutorGUI();
                ttg.setVisible(true);
                ttg.initialize();
            }
        });
    }
    
    //initialize JButtons into array and sets background colour for all buttons
    public void initialize()
    {
        //Put all buttons into array
        buttons = new JButton[]{tildeBtn, bBtn, aBtn, apostropheBtn, backSlashBtn, backSpaceBtn, cBtn, capsBtn, 
            commaBtn, dBtn, downBtn, eBtn, eightBtn, equalsBtn, fBtn, fiveBtn, 
            fourBtn, gBtn, hBtn, hyphenBtn, iBtn, jBtn, kBtn, lBtn, leftBracketBtn, 
            leftBtn, mBtn, nBtn, nineBtn, oBtn, oneBtn, pBtn, periodBtn, qBtn, 
            questionMarkBtn, rBtn, returnBtn, rightBracketBtn, rightBtn, sBtn, 
            semiColonBtn, sevenBtn, shiftBtn, sixBtn, spaceBtn, tBtn, tabBtn, 
            threeBtn, twoBtn, uBtn, upBtn, vBtn, wBtn, xBtn, yBtn, 
            zBtn, zeroBtn};
        
        //set all button background colours to a default color
        for(JButton button : buttons)
        {
            button.setBackground(origColor);
        }
        textArea.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aBtn;
    private javax.swing.JLabel accuracyLabel;
    private javax.swing.JLabel accuracyValue;
    private javax.swing.JButton apostropheBtn;
    private javax.swing.JButton bBtn;
    private javax.swing.JButton backSlashBtn;
    private javax.swing.JButton backSpaceBtn;
    private javax.swing.JButton cBtn;
    private javax.swing.JButton capsBtn;
    private javax.swing.JButton commaBtn;
    private javax.swing.JLabel correctCharactersLabel;
    private javax.swing.JLabel correctCharactersValue;
    private javax.swing.JButton dBtn;
    private javax.swing.JComboBox difficultyComboBox;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JButton downBtn;
    private javax.swing.JButton eBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton equalsBtn;
    private javax.swing.JButton fBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JButton gBtn;
    private javax.swing.JButton hBtn;
    private javax.swing.JButton hyphenBtn;
    private javax.swing.JButton iBtn;
    private javax.swing.JLabel incorrectCharactersLabel;
    private javax.swing.JLabel incorrectCharactersValue;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton jBtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kBtn;
    private javax.swing.JPanel keyboardPanel;
    private javax.swing.JButton lBtn;
    private javax.swing.JButton leftBracketBtn;
    private javax.swing.JButton leftBtn;
    private javax.swing.JButton mBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton nBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JButton oBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton pBtn;
    private javax.swing.JButton periodBtn;
    private javax.swing.JButton qBtn;
    private javax.swing.JButton questionMarkBtn;
    private javax.swing.JButton rBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton rightBracketBtn;
    private javax.swing.JButton rightBtn;
    private javax.swing.JButton sBtn;
    private javax.swing.JButton semiColonBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton shiftBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton spaceBtn;
    private javax.swing.JButton tBtn;
    private javax.swing.JButton tabBtn;
    private javax.swing.JTextPane textArea;
    private javax.swing.JLabel textLabel;
    private javax.swing.JPanel textPanel;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton tildeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JButton uBtn;
    private javax.swing.JButton upBtn;
    private javax.swing.JButton vBtn;
    private javax.swing.JButton wBtn;
    private javax.swing.JButton xBtn;
    private javax.swing.JButton yBtn;
    private javax.swing.JButton zBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables

    JButton buttons[]; //all buttons onscreen
    DecimalFormat twoDigits = new DecimalFormat("0.00");
    Color origColor = new Color(200, 200, 200); //default button background colour
    Color darkGreen = new Color(0, 150, 0);
    Color darkRed = new Color(150, 0, 0);
    int letterIndex = 0, correctChars = 0, incorrectChars = 0;
    double numberOfChars, accuracyRating; // holds user accuracy rating
    String pangram = "";
    String incorrectLetters = "Keys Your Having Trouble With: ";
    String correctText, incorrectText;
    
    @Override
    public void keyTyped(KeyEvent e) //When UNICODE character represented by key is sent from keyboard to system input
    {
        try
        {
            if (letterIndex <= pangram.length())
            {
                    //Correct key typed
                    if (e.getKeyChar() == pangram.charAt(letterIndex))
                    {
                        correctText = e.getKeyChar()+"";
                        textArea.setText(textArea.getText()+correctText);

                        correctChars++;
                        correctCharactersValue.setText(correctChars+"");
                    }
                    //incorrect key typed
                    else 
                    {   
                        incorrectLetters += pangram.charAt(letterIndex)+", ";
                        noteLabel.setText(incorrectLetters);
                        incorrectChars++;
                        incorrectCharactersValue.setText(incorrectChars+"");
                        
                        for (JButton button : buttons)
                        {
                            button.setBackground(origColor);
                        }
                    }    
                numberOfChars = accuracyCalc(correctChars, incorrectChars);
                accuracyValue.setText(twoDigits.format(accuracyRating)+"%");
                letterIndex++;
            }
        } catch(java.lang.StringIndexOutOfBoundsException | java.lang.NullPointerException x){}
    }
    
    @Override
    public void keyPressed(KeyEvent e) //When key is pressed down
    {
        System.out.println("Key Code: "+e.getKeyCode());
        //highlight key pressed
        for (JButton button : buttons)
        {
            if (button.getText().equalsIgnoreCase(e.getKeyChar()+""))
            {
                button.setBackground(Color.cyan);
            }
        }
        
        //special keys
        switch(e.getKeyCode())
        {
            case 10: returnBtn.setBackground(Color.cyan);break;
            case 20: capsBtn.setBackground(Color.cyan);break;
            case 32: spaceBtn.setBackground(Color.cyan);break;
            case 192: tildeBtn.setBackground(Color.cyan);break;
            case 8: backSpaceBtn.setBackground(Color.cyan);break;
            case 47: questionMarkBtn.setBackground(Color.cyan);break;
            case 16: shiftBtn.setBackground(Color.cyan);break;
            case 38: upBtn.setBackground(Color.cyan);break;
            case 40: downBtn.setBackground(Color.cyan);break;
            case 37: leftBtn.setBackground(Color.cyan);break;
            case 39: rightBtn.setBackground(Color.cyan);break;
            default: break;
        }
    }

    @Override
    public void keyReleased(KeyEvent e) //When pressed key is released
    {
        if (!e.isActionKey())
        {
            for (JButton button : buttons)
            {
                if (button.getText().equalsIgnoreCase(e.getKeyChar()+""))
                {
                    button.setBackground(origColor);
                }
            }
        }
        
        //special keys
        switch(e.getKeyCode())
        {
            case 10: returnBtn.setBackground(origColor);break;
            case 20: capsBtn.setBackground(origColor);break;
            case 32: spaceBtn.setBackground(origColor);break;
            case 192: tildeBtn.setBackground(origColor);break;
            case 8: backSpaceBtn.setBackground(origColor);break;
            case 47: questionMarkBtn.setBackground(origColor);break;
            case 16: shiftBtn.setBackground(origColor);break;
            case 38: upBtn.setBackground(origColor);break;
            case 40: downBtn.setBackground(origColor);break;
            case 37: leftBtn.setBackground(origColor);break;
            case 39: rightBtn.setBackground(origColor);break;
            default: break;
        }
      
        //While charAt index is less than length of pangram
        try
        {
            if (letterIndex < pangram.length() && difficultyComboBox.getSelectedIndex() != 0)
            {
                //Highlight Next Key To Be Pressed On Key Release
                for (JButton button : buttons)
                {
                    if (button.getText().equalsIgnoreCase(pangram.charAt(letterIndex)+""))
                    {
                        button.setBackground(Color.green);
                    }
                    else if(pangram.charAt(letterIndex) == ' ')
                    {
                        spaceBtn.setBackground(Color.green);
                    }
                }
            }
            //charAt index is equal to length of panagram
            else if (letterIndex == pangram.length() && difficultyComboBox.getSelectedIndex() != 0)
            {
                for (JButton button : buttons)
                {
                    button.setEnabled(false);
                }
            }
        } catch(java.lang.NullPointerException n) {}
    }
    
    //Calculate users accuracy
    public double accuracyCalc(int correctChars, int incorrectChars)
    {
        return accuracyRating = ((correctChars * 100) / (double)(correctChars + incorrectChars));
    }

    //Reset everything to default when changing lesson
    private void resetWindow()
    {
        letterIndex = 0;
        correctChars = 0;
        incorrectChars = 0;
        numberOfChars = 0;
        accuracyRating = 0;
        pangram = "";
        incorrectLetters = "Keys Your Having Trouble With: ";
        textArea.setText("");
        noteLabel.setText("Note: Clicking The Buttons With Your Mouse Will Not Perform Any Action.");
        textLabel.setText("Type Some Text Using Your Keyboard. The Keys You Press Will Be Highlighted And The Text Will Be Displayed.");
        accuracyValue.setText("100%");
        correctCharactersValue.setText("0");
        incorrectCharactersValue.setText("0");
        for (JButton button : buttons)
        {
            button.setEnabled(true);
            button.setBackground(origColor);
        }
    }
}
